export { JSON_ERROR_RESPONSE } from './JSON_ERROR_RESPONSE';
export { VK_ERROR_RESPONSE } from './VK_ERROR_RESPONSE';
export { METHOD_ERROR_RESPONSE } from './METHOD_ERROR_RESPONSE';
export { SERVER_ERROR_RESPONSE } from './SERVER_ERROR_RESPONSE';
