export { SERVER_ERROR_RESPONSE } from './SERVER_ERROR_RESPONSE';
export { JSON_ERROR_RESPONSE } from './JSON_ERROR_RESPONSE';
export { VK_ERROR_RESPONSE } from './VK_ERROR_RESPONSE';
export { METHOD_ERROR_RESPONSE } from './METHOD_ERROR_RESPONSE';
export { OK_RESPONSE } from './OK_RESPONSE';
export { CONFIRMATION_RESPONSE } from './CONFIRMATION_RESPONSE';
